packages:
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": 26.0.0
  "@typescript/native-preview": 7.0.0-dev.20260621.1
  bumpp: 11.1.0
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: 0.2.1
  mdast-util-from-markdown: 2.0.3
  mdast-util-to-markdown: 2.1.2
  unified: 11.0.5
  "@types/mdast": 4.0.4
  micromark-util-types: 2.0.2
  micromark: 4.0.2
  unist-util-visit: 5.1.0
  unist-util-find-all-after: 5.0.0
  unist-util-find-before: 4.0.1
  unist-util-find-between: 1.2.2
  "@types/unist": 3.0.3
  unist-util-find-after: 5.0.0
  mdast-util-to-string: 4.0.0
  mdast-util-gfm-table: 2.0.0
  micromark-extension-gfm-table: 2.1.1
  rehype-stringify: 10.0.1
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  remark-lint: 10.0.1
  remark-gfm: 4.0.1
  unified-lint-rule: 3.0.1
  "@changesets/cli": 2.31.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260621.1"
  - "@typescript/native-preview@7.0.0-dev.20260621.1"
