name: Release

on:
  workflow_run:
    workflows:
      - "CI Build"
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write # for OIDC
      actions: read # for downloading artifacts

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true
      - run: vp install
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vp-build-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - run: npm install -g npm@11.15.0 # vite plus installs old version (v11.1.2) which lacks trusted publishers
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
          version: vp run version
