name: Release

on:
  workflow_run:
    workflows:
      - "CI Build"
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write # for OIDC
  actions: read # for downloading artifacts

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true
          registry-url: https://registry.npmjs.org
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: vp-build-artifact
          path: packages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - run: vp install
      - name: Debug OIDC
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN exists=$([ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] && echo yes || echo no)"
          node --version
          npm --version
          pnpm --version
          vp --version
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          publish-script: vp run release
          version-script: vp run version
          create-github-releases: true
